print('Olá, Mundo')
print('Sou a Gabriela')
print('Tenho 18 anos')
print('E vou fazer faculdade de...')
print('Publicidade e Propaganda')
print(' Trabalho com o marketing da Eurofarma')
print('Na unidade de negócios Hospitalar')
print(' Sou de Parelheiros, extremo sul da zona sul de SP')
print(' Prentendo futuramnete, quando já estiver formada, migrar para área de marketing automotivo ')
print('Ou marketing de moda, cosméticos, banco talvez, isso vou decidir daqui uns anos.')